export type SlackRenderedMessage = {
  text: string;
  blocks: Record<string, unknown>[];
};

export function formatSingleRunReport(
  payload: Record<string, unknown>,
  context?: { occurredAt?: string },
): string | SlackRenderedMessage {
  const summary = (payload["Test Summary"] as Record<string, unknown> | undefined) ?? undefined;
  const execution =
    (payload["Test Execution Summary"] as Record<string, unknown> | undefined) ?? undefined;
  const observations =
    (payload["Detailed Observations and Analysis"] as unknown[] | undefined) ?? undefined;

  if (!summary || !execution) {
    return formatValue(payload);
  }

  const testName = String(summary.test_name ?? "Performance Test");
  const environment = String(summary.environment ?? "N/A");
  const validationPassed = resolveValidationBadge(execution);

  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `Performance Test Report: ${testName}`,
      },
    },
    {
      type: "section",
      fields: [
        {
          type: "mrkdwn",
          text: `*Environment:*\n${environment}`,
        },
        {
          type: "mrkdwn",
          text: `*Status:*\n${validationPassed}`,
        },
      ],
    },
  ];

  if (summary) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: formatSummaryMetricsAsMarkdown(summary),
      },
    });

    const aggregateTable = formatAggregateTableAsMarkdown(summary);
    if (aggregateTable) {
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: aggregateTable,
        },
      });
    }
  }

  if (execution) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: formatExecutionAsMarkdown(execution),
      },
    });
  }

  if (Array.isArray(observations) && observations.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Analysis & Observations*\n${observations.map((line) => `• ${String(line)}`).join("\n")}`,
      },
    });
  }

  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `*Senior Architect Review*\n${buildSeniorReviewLine(validationPassed)}`,
    },
  });

  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: buildEmailDraftMarkdown(testName, context?.occurredAt),
    },
  });

  blocks.push({
    type: "divider",
  });

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: "_Generated by Performance Orchestration AI_",
      },
    ],
  });

  return {
    text: `Performance Test Report: ${testName} (${validationPassed})`,
    blocks,
  };
}

function buildSeniorReviewLine(validationBadge: string): string {
  if (validationBadge === "✓ PASSED") {
    return "As Senior Architect Performance Engineer, this review indicates the run is healthy and suitable for stakeholder circulation.";
  }
  if (validationBadge === "! TARGET MISSED") {
    return "As Senior Architect Performance Engineer, this review is good from a stability perspective; however, expected throughput target was missed and requires capacity tuning before sign-off.";
  }
  return "As Senior Architect Performance Engineer, this review identifies critical issues that must be remediated before wider communication or rollout.";
}

function buildEmailDraftMarkdown(testName: string, occurredAt?: string): string {
  const reportDate = formatReportDate(occurredAt);
  const subject = `${testName} ${reportDate}`;
  return (
    `*Email Draft (Ready to Send)*\n` +
    `Subject: ${subject}\n\n` +
    `Hello Team,\n\n` +
    `Please find the reviewed performance report for ${testName} executed on ${reportDate}. ` +
    `The attached summary includes validation checks, aggregate metrics, and architect-level observations.\n\n` +
    `Regards,\n` +
    `Senior Architect Performance Engineer`
  );
}

function formatReportDate(occurredAt?: string): string {
  const parsed = occurredAt ? new Date(occurredAt) : new Date();
  if (Number.isNaN(parsed.getTime())) {
    const fallback = new Date();
    return `${fallback.getUTCFullYear()}-${String(fallback.getUTCMonth() + 1).padStart(2, "0")}-${String(fallback.getUTCDate()).padStart(2, "0")}`;
  }
  return `${parsed.getUTCFullYear()}-${String(parsed.getUTCMonth() + 1).padStart(2, "0")}-${String(parsed.getUTCDate()).padStart(2, "0")}`;
}

function formatSummaryMetricsAsMarkdown(summary: Record<string, unknown>): string {
  const transactions = Number(summary.transactions ?? 0);
  const throughput = Number(summary.throughput ?? 0);
  const avgMs = summary.response_times ? (summary.response_times as Record<string, unknown>).avg_ms : 0;
  const p95Ms = summary.response_times ? (summary.response_times as Record<string, unknown>).p95_ms : 0;
  const errorPct = Number(summary.error_rate_pct ?? 0);

  return (
    `*JMeter Test Metrics*\n` +
    `• *Samples:* ${transactions}\n` +
    `• *Throughput:* ${throughput.toFixed(2)} req/sec\n` +
    `• *Avg Response:* ${Number(avgMs).toFixed(2)} ms\n` +
    `• *P95 Response:* ${Number(p95Ms).toFixed(2)} ms\n` +
    `• *Error Rate:* ${errorPct.toFixed(2)}%`
  );
}

function formatAggregateTableAsMarkdown(summary: Record<string, unknown>): string {
  const aggregate = Array.isArray(summary.jmeter_aggregate)
    ? (summary.jmeter_aggregate as Record<string, unknown>[])
    : [];
  if (aggregate.length === 0) {
    return "";
  }

  const rows = aggregate.map((row) => {
    return `${String(row.label ?? "UNNAMED")} | ${Number(row.samples ?? 0)} | ${Number(row.average_ms ?? 0).toFixed(2)} | ${Number(row.median_ms ?? 0).toFixed(2)} | ${Number(row.p90_ms ?? 0).toFixed(2)} | ${Number(row.p95_ms ?? 0).toFixed(2)} | ${Number(row.p99_ms ?? 0).toFixed(2)} | ${Number(row.max_ms ?? 0).toFixed(2)} | ${Number(row.error_pct ?? 0).toFixed(2)} | ${Number(row.throughput_per_sec ?? 0).toFixed(2)}`;
  });

  return [
    "*JMeter Aggregate Report*",
    "```",
    "Label | Samples | Avg(ms) | Median(ms) | P90(ms) | P95(ms) | P99(ms) | Max(ms) | Error% | Throughput/s",
    "----- | ------- | ------- | ---------- | ------- | ------- | ------- | ------- | ------ | ------------",
    ...rows,
    "```",
  ].join("\n");
}

function formatExecutionAsMarkdown(execution: Record<string, unknown>): string {
  const testPlan = String(execution.test_plan_path ?? "N/A");
  const duration = Number(execution.duration_minutes ?? 0);
  const thresholdChecks = execution.threshold_checks as Record<string, boolean> | undefined;
  const targetChecks = execution.target_checks as Record<string, boolean> | undefined;

  let checksText = "*Validation Checks*\n";
  if (thresholdChecks) {
    for (const [key, passed] of Object.entries(thresholdChecks)) {
      const icon = passed ? "✓" : "✗";
      checksText += `• ${icon} ${key}\n`;
    }
  }
  if (targetChecks) {
    for (const [key, passed] of Object.entries(targetChecks)) {
      const icon = passed ? "✓" : "✗";
      checksText += `• ${icon} ${key}\n`;
    }
  }

  return (
    `*Test Execution*\n` +
    `• *Plan:* ${testPlan}\n` +
    `• *Duration:* ${duration} minutes\n\n` +
    checksText
  );
}

function resolveValidationBadge(execution: Record<string, unknown>): string {
  if (execution.validation_passed === true) {
    return "✓ PASSED";
  }

  const thresholdChecks = execution.threshold_checks as Record<string, boolean> | undefined;
  const targetChecks = execution.target_checks as Record<string, boolean> | undefined;
  const thresholdsPassed =
    thresholdChecks && Object.values(thresholdChecks).length > 0
      ? Object.values(thresholdChecks).every((value) => value === true)
      : false;
  const hasTargetMiss =
    targetChecks && Object.values(targetChecks).length > 0
      ? Object.values(targetChecks).some((value) => value === false)
      : false;

  if (thresholdsPassed && hasTargetMiss) {
    return "! TARGET MISSED";
  }

  return "✗ FAILED";
}

function formatValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.map((item) => `- ${formatValue(item)}`).join("\n");
  }
  if (value && typeof value === "object") {
    return Object.entries(value as Record<string, unknown>)
      .map(([key, nested]) => `${key}: ${formatValue(nested)}`)
      .join("\n");
  }
  return String(value);
}
